label_path: /data/hjl/projects/BiomedCLIP-PUNCE/datatools/gc-2000/onetask_9_labels
num_task: 1
num_classes:
  - 9
class_labels:
  - ['NILM', 'ASC-US', 'LSIL', 'ASC-H', 'HSIL', 'AGC', 'T', 'M', 'BV']


